### ISSUE TITLE
function only called by __init may be analyzed as outside

### ISSUE THREAD

**Issue by dtcccc** [aliyun/plugsched#129]
There exists an extremely rare condition:
bpf_iter_unreg_target() <- bpf_iter_unregister() <- ip6_route_cleanup() <- inet6_init()

Here inet6_init() is __init function, and others are only called by it.
However, the current inflect algorithm only tests whether the caller of  bpf_iter_unreg_target() is __init, not taking the whole call chain into account. Then bpf_iter_unreg_target() is analyzed as an outside function.

This issue is not important or urgent. We just record it here.

**Comment by chenshanpei** [comment]
To check whether all functions in call chain are __init, will let inflection algorithm becomes very complex. Close it as wontfix.
