### ISSUE TITLE
handle the condition that an interface function has both strong and weak symbol

### ISSUE THREAD

**Issue by dtcccc** [aliyun/plugsched#138]
This kind of functions should only keep the strong one and drop the weak one, or export_jump.h will be generated with two lines of the same function and cause errors when building.

e.g., bpf_event_output() is both defined at kernel/bpf/core.c and kernel/trace/bpf_trace.c.

**Comment by chenshanpei** [comment]
Weak symbols resemble global symbols, but their definitions have lower precedence.
