### ISSUE TITLE
GCC optimization may cause failure when collecting struct

### ISSUE THREAD

**Issue by dtcccc** [aliyun/plugsched#141]
For union bpf_attr, when visiting attr->bpf_fd || attr->file_flags, GCC will optimize these two u32 to one u64.

i.e., attr->bpf_fd & 0xBEEF || attr->file_flags & 0xDEAD
will become
tmp = \*(struct unnamed_struct\*)((unsigned long)attr+8)
tmp | 0xdead0000beef

and then op.field.name is None and cause sorting error.

**Comment by chenshanpei** [comment]
For any complex union or structure, we can **ignore the real name** of the members and use a **fixed fake name** instead. In thies case, the most important information is union name bpf_attr.
