### ISSUE TITLE
Some init functions are placed in .ref.text section.

### ISSUE THREAD

**Issue by Dengerwei** [aliyun/plugsched#49]
# Background
We determine whether a function is an init function by whether it is defined in the .init.text section. But there are some init functions are placed in .ref.text section and the plugin does not currently recognize this.

# Task
 Mark functions placed in .ref.text section as init functions.

**Comment by zxpdemonio** [comment]
The functions in .ref.text section have keyword: __ref, which means this functions will reference  init code or data. If the function with __ref references init code or data of kernel, it will cause crash when it's called, and we have to remove it from our module. If it references init code or data of plugsched module, it is ok to keep it in .ref.text section, as it is not init function actually.
