### ISSUE TITLE
Fail to initialize gcc python plugin

### ISSUE THREAD

**Issue by chenshanpei** [aliyun/plugsched#58]
When I try to use master branch, it doesn't work in old container images now. Then, I try to build the latest image at local, but soon meet a bug.   

steps to reproduce:
1.  build docker image: docker build -f Dockerfile.x86_64 . 
2.  start container with local image;
3.  ./cli.py dev_init ../ck ../sched_mod;

![lQLPJxZ90x-vpk7Mz80D2bCDA0fzGHze5ALPN63rgIcA_985_207](https://user-images.githubusercontent.com/24544596/178698180-f7d8207a-3ad2-445f-8990-823a95ae53f4.png)

**Comment by Dengerwei** [comment]
The reason for this problem is that the gcc-python-plugin-0.17-1.2 is built in anolis 8.6 system and the yum Plus repo is shared between 8.4 and 8.6. So the gcc-python-plugin-0.17-1.2 does not work in anolis 8.4.
