### ISSUE TITLE
EXPORT_SYMBOL_GPL is removed from the macro definition, leaving an undesired backslash at the EOL

### ISSUE THREAD

**Issue by ampresent** [aliyun/plugsched#68]
# Background
This bug is observed in another subsystem than scheduler. 

```c
#define XXX(x)                        \
    void x(int arg)                   \
    {                                 \
        BODY                          \
    }                                 \
    EXPORT_SYMBOL_GPL(x)
```

If we simply remove EXPORT_SYMBOL_GPL. It leaves an undesired backslash behind }.

# Task
Figure out the solution. A potential one is to `#define __DISABLE_EXPORTS`, which however restraints the module from defining new export function easily in the future.

**Comment by chenshanpei** [comment]
__DISABLE_EXPORTS does exest in old kernel (such as 3.10 and 4.19), so it's not an general solution.
